p1 = input('digite alguma coisa: ')
s1 = (type(p1))
print('Esse tipo primitivo é', s1)
print('é um número?', p1.isnumeric())
print('é alfabético?', p1.isalpha())
print('é um alfanumérico?', p1.isalnum())
print('Tem letras maiuscula?', p1.isupper())
print('tem letras minúsculas', p1.islower())
print('tem espaços?', p1.isspace())
