serieb = (' ', 'Sport', 'Gremio', 'Vasco', 'Bahia', 'Nautico', 'Chapecoense', 'Tombense', 'Ponte Preta', 'Cruzeiro', 'CRB', 'CSA', 'Brusque', 'Sampaio Correia', 'Criciuma', 'Guarani', 'Ituano', 'Novorizontino', 'Operario', 'Vila Nova', 'Tombense', 'Londrina')
print('='*30)
print('Brasileirao Serie B 2022')
print('='*30)
print(f'A lista Dos Times que Irao Competir a Serie B {serieb[1:20]}')
print('='*30)
print(f'O g5 e Formado Por {serieb[1:5]}')
print('='*30)
print(f'O Z4 e Formado por {serieb[17:20]}')
print('='*30)
print(f'A Lista dos Times em Ordem {sorted(serieb[1:20])}')
print('='*30)
print(f'O CSA Esta na {serieb.index("CSA")}° Posiçao')


